import type { uk } from './uk';

export const en: typeof uk = {
  nav: { work: 'Work', services: 'Services', about: 'About', contact: 'Contact' },
  common: { menu: 'Menu', close: 'Close', theme: 'Change theme', language: 'Перейти українською', available: 'Available for selected projects', unavailable: 'Currently booked', viewProject: 'Open case study', live: 'Live demo', github: 'GitHub', copied: 'Copied', copyEmail: 'Copy email', backHome: 'Back home', demoLabel: 'Demo content', confirmedLabel: 'Confirmed project', previous: 'Previous', next: 'Next' },
  home: {
    eyebrow: 'Full-stack JavaScript / Ukraine', titleA: 'Web products built', titleB: 'to do the work.', intro: 'I design and build legible websites, internal tools, and commerce demos—from the first flow to a verified release.', primaryCta: 'Discuss a project', secondaryCta: 'View work',
    workTitle: 'Selected work', workIntro: 'Functionality, constraints, and decisions—without invented metrics.', servicesTitle: 'Ways I can help', servicesIntro: 'A clear scope, working result, and a handoff that does not create developer dependence.', processTitle: 'How the work moves', evidenceTitle: 'Technology matters when it proves an outcome.', evidenceBody: 'React and state management for complex interfaces. Node.js and SQL for verified business flows. Automation for tests, deployment, and repeatable demos.', aboutTitle: 'Reliable communication. Working demos. Honest limits.', aboutBody: 'I break work into verifiable stages, show progress, and label what is not production-ready yet.', inquiryTitle: 'Have a problem worth taking to a working result?', inquiryBody: 'Share the context, timeline, and desired outcome. I will reply with the next practical step.',
  },
  services: {
    landing: { title: 'Product landing pages', body: 'Page strategy, design system, responsive build, and inquiry analytics.' }, tools: { title: 'Business tools', body: 'Portals, dashboards, internal workflows, roles, and reliable APIs.' }, commerce: { title: 'E-commerce & demos', body: 'Catalogs, carts, checkout flows, and integration prototypes.' }, fixes: { title: 'Fixes & deployment', body: 'Diagnosis, stabilisation, CI, hosting, and a post-release verification flow.' },
  },
  process: { discovery: 'Discovery', scope: 'Scope', prototype: 'Prototype', implementation: 'Build', verification: 'Verification', handoff: 'Handoff' },
  about: { eyebrow: 'About', title: 'A developer who keeps the product in view.', lead: 'I work on JavaScript products for small businesses, teams, and agencies. My strongest work connects a precise interface to real server-side logic.', principles: 'Principles', style: 'Working style', learning: 'Currently learning', stack: 'Working stack', resume: 'Download résumé (placeholder)', principleItems: ['Show progress through working flows', 'Surface risks before they become expensive', 'Document the handoff and next steps'], styleBody: 'Short cycles, recorded scope, regular demos, and real-device verification before handoff.', learningBody: 'Production React architecture, reliable integrations, and practical AI-assisted workflows.' },
  contact: { eyebrow: 'New project', title: 'Start with the context.', intro: 'The form helps establish the shape of the work quickly. No sales calls or manufactured urgency.', projectType: 'Project type', budget: 'Indicative budget', deadline: 'Preferred deadline', method: 'Preferred contact', name: 'Your name', email: 'Email', brief: 'Project brief', submit: 'Send inquiry', sending: 'Sending…', typeOptions: ['Landing page', 'Web application', 'E-commerce', 'Fix / deployment', 'Other'], budgetOptions: ['Under $500', '$500–1,000', '$1,000–3,000', '$3,000+', 'Not defined yet'], methodOptions: ['Email', 'Telegram'], availability: 'I am taking a limited number of new projects. Typical response time is 1–2 business days.', consent: 'By submitting, you agree to data processing for the purpose of responding to your inquiry.', error: 'The form could not be sent. Try again or email directly.' },
  case: { context: 'Context', challenge: 'Challenge & constraints', responsibilities: 'Responsibilities', flows: 'Key product flows', architecture: 'Architecture', gallery: 'Product screens', decisions: 'Decisions & tradeoffs', verification: 'Verification evidence', outcome: 'Confirmed outcome', unavailable: 'Link will be added after verification.' },
  privacy: { title: 'Privacy', body: 'Form data is used only to respond to your inquiry. It is not sold or used for promotional mailing. Technical hosting may temporarily process request logs for security. To request deletion, email the address listed on this site.' },
  thankYou: { title: 'Inquiry received.', body: 'Thank you for the context. I will review the details and respond within 1–2 business days.' },
  notFound: { code: '404 / ROUTE NOT FOUND', title: 'This page moved beyond the grid.', body: 'The address changed or the page does not exist.' },
  footer: { note: 'Designed and built with attention to detail.', privacy: 'Privacy' },
};
